/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type EntityType = "activity" | "event" | "person" | "place" | "topic";

export type Json = ColumnType<JsonValue, string, string>;
export type JsonArray = JsonValue[];
export type JsonObject = { [x: string]: JsonValue | undefined };
export type JsonPrimitive = boolean | number | string | null;
export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type SuggestionAction = "accepted" | "dismissed" | "edited" | "shown";

export type SuggestionSource = "ai" | "history" | "offline" | "prompt";

export type TaskStatus = "done" | "in_progress" | "todo";

/** How a task repeats; a TEXT column with a CHECK (migration 010). */
export type ReminderRepeat = "daily" | "monthly" | "weekdays" | "weekly";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface NoteEntities {
  aliases: Generated<string[]>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  normalizedName: string;
  noteId: string;
  type: EntityType;
  userId: number;
}

export interface NoteProjects {
  createdAt: Generated<Timestamp>;
  noteId: string;
  projectId: string;
  userId: number;
}

/** A link between a note and a task; many to many. */
export interface NoteTasks {
  createdAt: Generated<Timestamp>;
  noteId: string;
  taskId: string;
  userId: number;
}

/** The cached AI summary of a task's notes and focus time. */
export interface TaskSummaries {
  createdAt: Generated<Timestamp>;
  inputHash: string;
  /** JSON text: [{ date: "YYYY-MM-DD", text: string }], oldest first. */
  progress: Generated<string>;
  summary: string;
  taskId: string;
  userId: number;
}

export interface Notes {
  archived: Generated<boolean>;
  content: Generated<string>;
  /** The rich text as the editor keeps it (Tiptap JSON); null before rich text or after a plain edit. */
  doc: Json | null;
  createdAt: Generated<Timestamp>;
  entitiesHash: string | null;
  id: Generated<string>;
  source: NoteSource | null;
  /** For a thought parked during focus time: the task being worked on. */
  taskId: string | null;
  title: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export type NoteSource = "focus" | "page";

export type FocusOutcome = "finished" | "progress" | "stuck";

export interface FocusSessions {
  createdAt: Generated<Timestamp>;
  endedAt: Generated<Timestamp>;
  firstStep: Generated<string>;
  focusedSeconds: number;
  id: Generated<string>;
  leftOff: Generated<string>;
  outcome: FocusOutcome;
  plannedMinutes: number;
  startedAt: Timestamp;
  taskId: string;
  userId: number;
}

export interface Projects {
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  normalizedName: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface SuggestionEvents {
  action: SuggestionAction;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  noteId: string | null;
  responseMs: number | null;
  source: SuggestionSource;
  suggestionText: string;
  userId: number;
}

export interface TaskExtractions {
  contentHash: string;
  extractedAt: Generated<Timestamp>;
  noteId: string;
  userId: number;
}

export type TaskSuggestionStatus = "dismissed" | "pending";

/** Find tasks' suggestions, kept until the writer adds or dismisses them (migration 014). */
export interface TaskSuggestions {
  completeBy: Timestamp | null;
  createdAt: Generated<Timestamp>;
  fingerprint: string;
  id: Generated<string>;
  noteId: string;
  projectName: Generated<string>;
  status: Generated<TaskSuggestionStatus>;
  text: string;
  userId: number;
}

export interface Tasks {
  completeBy: Timestamp | null;
  /** When it was done; null while it isn't (migration 014). */
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  description: Generated<string>;
  id: string;
  noteId: string | null;
  /** The task's time on its day, "HH:MM" on the writer's clock (migration 011). */
  dueTime: string | null;
  /** The day it was planned for before a move pushed it on (migration 014). */
  movedFrom: Timestamp | null;
  projectId: string;
  /** Minutes before the task's time (or 9:00 on its day) to remind (migration 011). */
  remindBefore: number | null;
  remindRepeat: ReminderRepeat | null;
  /** The reminder is for this time only: when the repeating task comes back, it has none (migration 016). */
  remindOnce: Generated<boolean>;
  sourceFingerprint: string | null;
  status: Generated<TaskStatus>;
  text: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface UserPreferences {
  updatedAt: Generated<Timestamp>;
  usePersonalization: Generated<boolean>;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  clerkId: string;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  focusSessions: FocusSessions;
  noteEntities: NoteEntities;
  noteProjects: NoteProjects;
  notes: Notes;
  noteTasks: NoteTasks;
  projects: Projects;
  suggestionEvents: SuggestionEvents;
  taskExtractions: TaskExtractions;
  taskSuggestions: TaskSuggestions;
  taskSummaries: TaskSummaries;
  tasks: Tasks;
  userPreferences: UserPreferences;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const EntityTypeArrayValues: [EntityType, ...EntityType[]] = ["activity","event","person","place","topic"];
export const SuggestionSourceArrayValues: [SuggestionSource, ...SuggestionSource[]] = ["ai","history","offline","prompt"];
export const SuggestionActionArrayValues: [SuggestionAction, ...SuggestionAction[]] = ["accepted","dismissed","edited","shown"];
export const NoteSourceArrayValues: [NoteSource, ...NoteSource[]] = ["focus","page"];
export const TaskSuggestionStatusArrayValues: [TaskSuggestionStatus, ...TaskSuggestionStatus[]] = ["dismissed","pending"];
export const FocusOutcomeArrayValues: [FocusOutcome, ...FocusOutcome[]] = ["finished","progress","stuck"];
export const TaskStatusArrayValues: [TaskStatus, ...TaskStatus[]] = ["done","in_progress","todo"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.