/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type EntityType = "activity" | "event" | "person" | "place" | "topic";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type SuggestionAction = "accepted" | "dismissed" | "edited" | "shown";

export type SuggestionSource = "ai" | "history" | "offline" | "prompt";

export type TaskStatus = "done" | "in_progress" | "todo";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface NoteEntities {
  aliases: Generated<string[]>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  normalizedName: string;
  noteId: string;
  type: EntityType;
  userId: number;
}

export interface Notes {
  archived: Generated<boolean>;
  content: Generated<string>;
  createdAt: Generated<Timestamp>;
  entitiesHash: string | null;
  id: Generated<string>;
  title: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Projects {
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  normalizedName: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface SuggestionEvents {
  action: SuggestionAction;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  noteId: string | null;
  responseMs: number | null;
  source: SuggestionSource;
  suggestionText: string;
  userId: number;
}

export interface TaskExtractions {
  contentHash: string;
  extractedAt: Generated<Timestamp>;
  noteId: string;
  userId: number;
}

export interface Tasks {
  completeBy: Timestamp | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: string;
  noteId: string | null;
  projectId: string;
  sourceFingerprint: string | null;
  status: Generated<TaskStatus>;
  text: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface UserPreferences {
  updatedAt: Generated<Timestamp>;
  usePersonalization: Generated<boolean>;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  clerkId: string;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  noteEntities: NoteEntities;
  notes: Notes;
  projects: Projects;
  suggestionEvents: SuggestionEvents;
  taskExtractions: TaskExtractions;
  tasks: Tasks;
  userPreferences: UserPreferences;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const EntityTypeArrayValues: [EntityType, ...EntityType[]] = ["activity","event","person","place","topic"];
export const SuggestionSourceArrayValues: [SuggestionSource, ...SuggestionSource[]] = ["ai","history","offline","prompt"];
export const SuggestionActionArrayValues: [SuggestionAction, ...SuggestionAction[]] = ["accepted","dismissed","edited","shown"];
export const TaskStatusArrayValues: [TaskStatus, ...TaskStatus[]] = ["done","in_progress","todo"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.